server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service} # declare environment variables ${edit:default}
    username : ${DBMS_USERNAME:root}
    password : ${DBMS_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
    signerKey: "SE1f0TDucS8RvuRNvX+EHYc5VeBEJH1BVJQs8zIhgtqFU343Wo3Qdkw3QavKD0eP"
    expiration-duration: 3600 # in seconds
    refreshable-duration: 360000 # in seconds
app:
  services:
    profile: http://localhost:8081/profile/