server:
  port: 8888
app:
  api-prefix: /api/v1
spring:
  application:
    name: api-gateway
  cloud:
      gateway:
          routes:
            - id : identity_service
              uri: http://localhost:8080
              predicates:
                - Path=${app.api-prefix}/identity/**
              filters:
                - StripPrefix=2
            - id: profile_service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-prefix}/profile/users/** # không th? truy c?p vào internal
              filters:
                - StripPrefix=2 # c?t ?i 1 api ví d? ? trên là c?t /api/ -> ch? còn /profile/**