server:
#  set different port with another services
  port: 8081
  servlet:
    context-path: /profile
spring:
  neo4j:
    uri: ${NE4J_CONNECTION:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:@Linh2003}